create table Client(
    id int generated by default as identity primary key ,
    name varchar(100)not null ,
    surname varchar(100)not null ,
    age int not null
);

create table Account(
    id int generated by default as identity primary key ,
    email varchar(100) not null ,
    password varchar(100) not null ,
    client_id int references Client(id) on delete set null
);


drop table Client;

drop table Account;


